package com.software_project_team_15b.Ticketmaster.Domain.Notification;

import java.time.Instant;
import java.util.UUID;
import java.util.Objects;

import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.Column;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;

/**
 * Persistent representation of a notification targeted at a single user.
 *
 * <p>A row is stored when a notification cannot be delivered immediately (the
 * recipient is offline). When the user reconnects the stored, unread notifications
 * are replayed to them and marked as {@link #isRead() read}. Notifications that are
 * delivered live to an online user are not persisted.</p>
 */
@Entity
@Table(name = "notifications")
public class NotificationEntity {

    /** Surrogate primary key, generated by the persistence provider. */
    @Id
    @GeneratedValue
    private UUID id;

    /** Identifier of the user this notification is addressed to. */
    @Column(name = "user_id", nullable = false, updatable = false)
    private UUID userId;

    /** Category of the notification. */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, updatable = false)
    private NotificationType type;

    /** Short human-readable headline. */
    @Column(nullable = false, updatable = false)
    private String title;

    /** Full human-readable body (bounded length for storage). */
    @Column(length = 2000)
    private String message;

    /** The instant the notification was created. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /** Whether the notification has already been delivered to and seen by the user. */
    @Column(name = "is_read", nullable = false)
    private boolean read = false;

    /** No-args constructor required by JPA; not for application use. */
    protected NotificationEntity() {}

    /**
     * Creates a new, unread notification for the given user.
     *
     * @param userId    identifier of the recipient user
     * @param type      category of the notification
     * @param title     short human-readable headline
     * @param message   full human-readable body
     * @param createdAt the instant the notification was created
     */
    public NotificationEntity(UUID userId,
                              NotificationType type,
                              String title,
                              String message,
                              Instant createdAt) {
        this.userId = Objects.requireNonNull(userId, "userId cannot be null");
        this.type = Objects.requireNonNull(type, "type cannot be null");
        this.title = Objects.requireNonNull(title, "title cannot be null");
        this.message = Objects.requireNonNull(message, "message cannot be null");
        this.createdAt = Objects.requireNonNull(createdAt, "createdAt cannot be null");

        if (title.isBlank()) {
            throw new IllegalArgumentException("title cannot be blank");
        }
        if (message.isBlank()) {
            throw new IllegalArgumentException("message cannot be blank");
        }
    }

    /** Marks this notification as read (delivered and seen). */
    public void markAsRead() {
        this.read = true;
    }

    /**
     * @return the generated primary key, or {@code null} if not yet persisted
     */
    public UUID getId() {
        return id;
    }

    /**
     * @return the identifier of the recipient user
     */
    public UUID getUserId() {
        return userId;
    }

    /**
     * @return the category of the notification
     */
    public NotificationType getType() {
        return type;
    }

    /**
     * @return the short human-readable headline
     */
    public String getTitle() {
        return title;
    }

    /**
     * @return the full human-readable body
     */
    public String getMessage() {
        return message;
    }

    /**
     * @return the instant the notification was created
     */
    public Instant getCreatedAt() {
        return createdAt;
    }

    /**
     * @return {@code true} if the notification has been delivered and seen
     */
    public boolean isRead() {
        return read;
    }
}