spring.application.name=Ticketmaster

app.storage.mode=${STORAGE_MODE:memory}
app.external.mode=${EXTERNAL_MODE:fake}

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.type.preferred_uuid_jdbc_type=CHAR
